version: '3.7'
services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:80"
  api:
    image: "api"
    build:
      context: .
      dockerfile: Dockerfile
