/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Auth: typeof import('./components/Auth.vue')['default']
    BuildImage: typeof import('./components/BuildImage.vue')['default']
    Camera: typeof import('./components/Camera.vue')['default']
    Chart: typeof import('./components/Chart.vue')['default']
    Chatbot: typeof import('./components/Chatbot.vue')['default']
    ChatbotAudio: typeof import('./components/ChatbotAudio.vue')['default']
    ChatbotIngest: typeof import('./components/ChatbotIngest.vue')['default']
    Dark: typeof import('./components/Dark.vue')['default']
    DatabaseKey: typeof import('./components/DatabaseKey.vue')['default']
    DeployChatbot: typeof import('./components/DeployChatbot.vue')['default']
    EventSource: typeof import('./components/EventSource.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    GithubButton: typeof import('./components/GithubButton.vue')['default']
    GithubRepository: typeof import('./components/GithubRepository.vue')['default']
    GithubSearch: typeof import('./components/GithubSearch.vue')['default']
    GithubTemplates: typeof import('./components/GithubTemplates.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    Notifier: typeof import('./components/Notifier.vue')['default']
    Post: typeof import('./components/Post.vue')['default']
    ProgressBar: typeof import('./components/ProgressBar.vue')['default']
    Request: typeof import('./components/Request.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./components/SideBar.vue')['default']
    SingleUpload: typeof import('./components/SingleUpload.vue')['default']
    Sse: typeof import('./components/Sse.vue')['default']
    Upload: typeof import('./components/Upload.vue')['default']
    User: typeof import('./components/User.vue')['default']
    Voice: typeof import('./components/Voice.vue')['default']
    WebSocket: typeof import('./components/WebSocket.vue')['default']
  }
}
